### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by moshekaplan** [d33tah/aflize#1]
When I run `docker run -ti d33tah/afl-sid` on my Ubuntu 16.04 x86, it downloads the files for the docker container and when it attempts to launch the container, displays the following error:

> FATA[0000] Error response from daemon: Cannot start container 11b1fc0eb7981af5dd2697290edc151903c1c34428077a358d7b2bae196acf87: [8] System error: exec format error

**Comment by d33tah** [comment]
@moshekaplan: how about `docker run -ti d33tah/afl-sid bash -l`? This way it would run `.bashrc` and `/etc/profile*`.

**Comment by d33tah** [comment]
By the way, perhaps it's because your arch is x86 not x86_64? You might want to try building the repo yourself.

**Comment by moshekaplan** [comment]
Same error when trying to run with `bash -l`. I got a similar error when trying to build the repo:

```
user@ubuntu1604:~/Desktop/$ git clone https://github.com/d33tah/aflize.git
user@ubuntu1604:~/Desktop/$ cd aflize
user@ubuntu1604:~/Desktop/$ sudo su
root@ubuntu1604:/home/user/Desktop/aflize# docker build -t d33tah/afl-sid .
Sending build context to Docker daemon 97.28 kB
Sending build context to Docker daemon 
Step 0 : FROM debian:sid
 ---> a81173cb26ab
Step 1 : RUN echo 'deb-src http://httpredir.debian.org/debian sid main' >> /etc/apt/sources.list
 ---> Using cache
 ---> 55bcb94f5737
Step 2 : RUN echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/no-suggests
 ---> Using cache
 ---> 1523493c4d0c
Step 3 : RUN echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/no-recommends
 ---> Using cache
 ---> cc464b1b2669
Step 4 : RUN apt-get update && apt-get install build-essential gcc g++ wget tar gzip make ca-certificates vim procps -y
 ---> Using cache
 ---> 12208c06b6a2
Step 5 : RUN wget 'http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz' -O- | tar zxvf - && cd afl-* && make PREFIX=/usr install
 ---> Using cache
 ---> 9d0d5f6d0a8d
Step 6 : ADD ./afl-sh-profile /etc/profile.d/afl-sh-profile
 ---> Using cache
 ---> 7bb449692c37
Step 7 : RUN ln -s /etc/profile.d/afl-sh-profile /etc/profile.d/afl-sh-profile.sh
 ---> Running in 926c456de7cf
exec format error
INFO[0000] [8] System error: exec format error          

```

**Comment by d33tah** [comment]
Does mean that it's `ln -s` that fails? Try running `docker build` without cache enabled. Also, it looks like someone wrote a 32-bit patch:

https://github.com/edmcman/aflize/commit/31570a48677abdc9009e8c49ac57d136b744c810

**Comment by moshekaplan** [comment]
No clue about the `ln -s`.

I get the following output when I add `--no-cache`:

```
root@ubuntu1604:/home/user/Desktop/aflize# docker build --no-cache=true -t d33tah/afl-sid .
Sending build context to Docker daemon 97.28 kB
Sending build context to Docker daemon 
Step 0 : FROM debian:sid
 ---> a81173cb26ab
Step 1 : RUN echo 'deb-src http://httpredir.debian.org/debian sid main' >> /etc/apt/sources.list
 ---> Running in bfe6a37800c6
exec format error
INFO[0000] [8] System error: exec format error    
```

I'll try using the 32-bit patch next. My interest in running aflize on x86 is because I don't have enough memory to run ASAN on a 64-bit system.

**Comment by d33tah** [comment]
@moshekaplan: I see. BTW, You might disable ASAN by unsetting `AFL_USE_ASAN`.

**Comment by moshekaplan** [comment]
The problem was caused by running docker on my x86 Ubuntu installation. I can open the docker container without issue on an x64 Ubuntu VM.

Thanks!
